name: CI

on: [pull_request]

jobs:
  pre:
    name: Prerequisites
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Enforce CLA signature
        env:
          COMMIT_RANGE: ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}
        run: curl https://raw.githubusercontent.com/shapesecurity/CLA/HEAD/cla-check.sh | bash

  build:
    name: Build
    needs: pre
    if: |
      !cancelled() && !failure()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          cache: 'maven'

      - name: Test
        run: |
          java -Xmx32m -version
          javac -J-Xmx32m -version
          mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          mvn test -B
